using SimAirport.Core;
using System.Collections.Generic;
using UnityEngine;

namespace SimAirport.AI {
	/// <summary>
	/// Manages flight schedules and triggers passenger spawning.
	/// For v0.0.1, this is a simple implementation.
	/// </summary>
	public class FlightManager : MonoBehaviour {
		// In a real implementation, this would be loaded from JSON
		private List<Flight> flightSchedule;

		private void Start() {
			// TODO: Load flight schedule from JSON data generated by Python
		}

		private void OnEnable() {
			//GameTimeManager.OnTick += HandleTick;
		}

		private void OnDisable() {
			//GameTimeManager.OnTick -= HandleTick;
		}

		private void HandleTick(float deltaSimMinutes) {
			// TODO: Check schedule and trigger passenger spawns via PassengerSpawner
		}
	}

	[System.Serializable]
	public class Flight {
		public string flight_id;
		public int time_minutes;
		public string gate;
		public int passengers;
	}
}